build: downgrade node-fetch to ^2.6.7
Due to v3.3 throwing a SyntaxError.

Error:
\node_modules\node-fetch\src\index.js:9
    import http from 'node:http';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

Source:
https://github.com/node-fetch/node-fetch/issues/1289#issuecomment-988472920