refactor: add next/router mock in Jest globalSetup
due to nested components with useRouter throwing errors in tests.

Error Message:
Error: Uncaught [Error: Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted]